services:
  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  server:
    build: ./packages/server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  client:
    build: ./packages/client
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  pgdata:
