services:
  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  server:
    build: ./packages/server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run migration:run && npm run start:prod"

  client:
    build: ./packages/client
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  pgdata:
