name: Build and Deploy to Cloud Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add server to known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan -p 223 -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh -p 223 $SSH_USER@$SSH_HOST "
            cd ~/tea-market &&
            git pull origin main &&
            docker compose down --rmi all &&
            docker compose up --build -d
          "
